package pokeball.archrules

import com.tngtech.archunit.core.domain.JavaClasses
import com.tngtech.archunit.core.importer.ClassFileImporter
import com.tngtech.archunit.core.importer.ImportOption
import com.tngtech.archunit.lang.ArchRule
import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals

/**
 * Each seeded fixture must be caught by the rule meant for it (and the clean
 * fixture and the real examples by none). The detection matrix is written to
 * `archrules-detection.md` in the directory selected by `pokeball.results`.
 */
class PokeballRulesTest {
    private val importer = ClassFileImporter().withImportOption(ImportOption { true })
    private fun load(pkg: String): JavaClasses = importer.importPackages(pkg)

    private fun violations(rule: ArchRule, classes: JavaClasses): Int =
        rule.evaluate(classes).failureReport.details.size

    private val fixtures = linkedMapOf(
        "clean (control)" to "pokeball.archrules.fixtures.clean",
        "reads System.currentTimeMillis" to "pokeball.archrules.fixtures.clock",
        "uses kotlin.random.Random" to "pokeball.archrules.fixtures.random",
        "reads a file (java.io)" to "pokeball.archrules.fixtures.io",
        "calls Thread.sleep" to "pokeball.archrules.fixtures.thread",
        "uses pokeball.runtime" to "pokeball.archrules.fixtures.runtimeuse",
        "calls Instant.now()" to "pokeball.archrules.fixtures.javatime",
        "top-level var (global state)" to "pokeball.archrules.fixtures.globalstate",
        "var property in state" to "pokeball.archrules.fixtures.varstate",
        "MutableList in state" to "pokeball.archrules.fixtures.mutablecollection",
    )

    /** Which rule each fixture is meant to trigger. */
    private val expected = mapOf(
        "reads System.currentTimeMillis" to "deciderPurity",
        "uses kotlin.random.Random" to "deciderPurity",
        "reads a file (java.io)" to "deciderPurity",
        "calls Thread.sleep" to "deciderPurity",
        "uses pokeball.runtime" to "deciderPurity",
        "calls Instant.now()" to "deciderPurity",
        "top-level var (global state)" to "noGlobalMutableState",
        "var property in state" to "immutableValues",
        "MutableList in state" to "immutableValues",
    )

    private fun rulesFor(classes: JavaClasses) = linkedMapOf(
        "deciderPurity" to PokeballRules.deciderPurity(classes),
        "noGlobalMutableState" to PokeballRules.noGlobalMutableState(classes),
        "immutableValues" to PokeballRules.immutableValues(classes),
    )

    @Test
    fun `every seeded violation is detected by its rule and the control passes`() {
        val rows = ArrayList<String>()
        var missed = 0
        for ((label, pkg) in fixtures) {
            // The clean control lives in the root fixtures package file.
            val classes = if (label.startsWith("clean")) load("pokeball.archrules.fixtures").that(com.tngtech.archunit.base.DescribedPredicate.describe("root fixture package") { it.packageName == "pokeball.archrules.fixtures" }) else load(pkg)
            val counts = rulesFor(classes).mapValues { (_, r) -> violations(r, classes) }
            val want = expected[label]
            val ok = if (want == null) counts.values.all { it == 0 } else counts.getValue(want) > 0
            if (!ok) missed++
            rows += "| $label | " + counts.values.joinToString(" | ") { if (it > 0) "detected ($it)" else "—" } + " | ${if (ok) "yes" else "**no**"} |"
        }
        val leak = PokeballRules.featuresUseOnlyPublicApis(
            mapOf(
                "pokeball.archrules.fixtures.featurea" to "pokeball.archrules.fixtures.featurea.api",
                "pokeball.archrules.fixtures.featureb" to "pokeball.archrules.fixtures.featureb.api",
            ),
        )
        val leakCount = violations(leak, load("pokeball.archrules.fixtures"))
        if (leakCount == 0) missed++
        rows += "| feature A uses feature B's implementation | — | — | — | ${if (leakCount > 0) "yes: featuresUseOnlyPublicApis detected ($leakCount)" else "**no**"} |"
        write(
            "# Architecture-rule detection matrix\n\n" +
                "Generated by `PokeballRulesTest` (`./gradlew :pokeball-archrules:test`). Each fixture package in " +
                "`pokeball-archrules/src/test/kotlin/pokeball/archrules/fixtures` seeds one kind of violation.\n\n" +
                "| Fixture | deciderPurity | noGlobalMutableState | immutableValues | Caught by the intended rule |\n|---|---|---|---|---|\n" +
                rows.joinToString("\n") + "\n",
        )
        assertEquals(0, missed, rows.joinToString("\n"))
    }

    @Test
    fun `the examples satisfy every rule`() {
        val examples = load("pokeball.examples")
        assertEquals(
            sortedSetOf(
                "pokeball.examples.catalog", "pokeball.examples.orderdraft", "pokeball.examples.shop.checkout",
                "pokeball.examples.shop.inventory", "pokeball.examples.shop.orders", "pokeball.examples.shop.payments",
            ),
            PokeballRules.deciderPackages(examples),
        )
        for (rule in PokeballRules.all(examples)) rule.check(examples)
        PokeballRules.featuresUseOnlyPublicApis(
            mapOf(
                "pokeball.examples.shop.payments" to "pokeball.examples.shop.payments.api",
                "pokeball.examples.shop.inventory" to "pokeball.examples.shop.inventory.api",
                "pokeball.examples.shop.orders" to "pokeball.examples.shop.orders.api",
                "pokeball.examples.shop.checkout" to "pokeball.examples.shop.checkout.api",
            ),
        ).check(examples)
    }

    @Test
    fun `the kernel depends only on the Kotlin standard library`() {
        PokeballRules.kernelIsSelfContained().check(load("pokeball.kernel"))
    }

    private fun write(text: String) {
        val dir = System.getProperty("pokeball.results") ?: return
        File(dir).mkdirs()
        File(dir, "archrules-detection.md").writeText(text)
    }
}
